name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        kotlin: [ '1.4.30', '1.5.0', '1.6.20', '1.7.20' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: set up Kotlin version
        run: sed -i 's/1.5.0/${{ matrix.kotlin }}/g' build.gradle
      - name: test
        run: ./gradlew test
